[package]
name = "mad_engine"
version = "0.1.0"
edition = "2021"
authors = ["Juguang Yan <coolyanjg@163.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-spdk = {path = "../async-spdk"}
crc = "3.0.0"
